version: '3.8'

services:
  dora-agent:
    build: .
    container_name: dora-agent
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./auth_info:/app/auth_info
      - ./data:/app/data
      - ./.env:/app/.env
      # Data akun Admin akan disimpan aman dalam volume khusus docker agar tidak terlihat sebagai file terbuka
      - dora_admin:/root

volumes:
  dora_admin:
